// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp_homework.Models.Data;

namespace asp_homework.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20190326145027_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("asp_homework_gui.Models.Data.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<int>("RoomId");

                    b.HasKey("ReservationId");

                    b.HasIndex("RoomId", "Date")
                        .IsUnique();

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            Date = new DateTime(2019, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "josef.novy@email.cz",
                            FirstName = "Josef",
                            LastName = "Nový",
                            PhoneNumber = "+420 724 393 339",
                            RoomId = 1
                        },
                        new
                        {
                            ReservationId = 2,
                            Date = new DateTime(2019, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karel.stary@email.cz",
                            FirstName = "Karel",
                            LastName = "Starý",
                            PhoneNumber = "+420 602 968 359",
                            RoomId = 1
                        },
                        new
                        {
                            ReservationId = 3,
                            Date = new DateTime(2019, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jindrich.novotny@email.cz",
                            FirstName = "Jindřich",
                            LastName = "Novotný",
                            PhoneNumber = "+420 724 013 313",
                            RoomId = 2
                        },
                        new
                        {
                            ReservationId = 4,
                            Date = new DateTime(2019, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.capka@email.cz",
                            FirstName = "David",
                            LastName = "Čapka",
                            PhoneNumber = "+420 724 676 776",
                            RoomId = 2
                        });
                });

            modelBuilder.Entity("asp_homework_gui.Models.Data.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<byte>("From");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte>("To");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Vivamus ac leo pretium faucibus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Pellentesque pretium lectus id turpis. Nullam faucibus mi quis velit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce tellus. Nam quis nulla. Phasellus faucibus molestie nisl. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante.",
                            From = (byte)9,
                            Name = "Alchemist's Chamber",
                            To = (byte)18
                        },
                        new
                        {
                            RoomId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Vivamus ac leo pretium faucibus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Pellentesque pretium lectus id turpis. Nullam faucibus mi quis velit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce tellus. Nam quis nulla. Phasellus faucibus molestie nisl. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante.",
                            From = (byte)8,
                            Name = "Path to Eternity",
                            To = (byte)20
                        },
                        new
                        {
                            RoomId = 3,
                            From = (byte)8,
                            Name = "Legacy of Ancestors",
                            To = (byte)19
                        });
                });

            modelBuilder.Entity("asp_homework_gui.Models.Data.Models.Reservation", b =>
                {
                    b.HasOne("asp_homework_gui.Models.Data.Models.Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
