using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace asp_homework.Models.Data.Models.HelperModels
{
    /// <summary>
    /// Represents the range in hours, for example: 10:00 - 13:00.
    /// The point if this class is, that more rooms can have same opening hours.
    /// It's not a database entity!
    /// </summary>
    [NotMapped]
    public class TimeRange
    {
        public int From { get; set; }
        public int To { get; set;  }

        public TimeRange(int from, int to)
        {
            From = from;
            To = to;
        }

        /// <summary>
        /// Checks if the two time intervals overlap each other
        /// </summary>
        /// <param name="other"></param>
        /// <returns></returns>
        public bool CollidesWith(TimeRange other)
        {
            return (From >= other.From && From <= other.To) ||
                   (To >= other.From && To <= other.To) ||
                   (From <= other.From && To >= other.To);
        }
        
        //Generated by IDE
        protected bool Equals(TimeRange other)
        {
            return From == other.From && To == other.To;
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != this.GetType()) return false;
            return Equals((TimeRange) obj);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return (From * 397) ^ To;
            }
        }
    }
}