using System;
using System.Collections.Generic;

namespace reservation_domain.Models.Range
{
    public class Range<T> where T : IComparable<T>
    {
        public T From { get; set; }
        public T To { get; set; }
        
        internal Range(T from, T to)
        {
            From = from;
            To = to;
        }
        
        /// <summary>
        /// Checks if the two objects don't collide
        /// </summary>
        /// <param name="other">The other object</param>
        /// <returns>true if the two objects collide otherwise false</returns>
        public bool CollidesWith(Range<T> other)
        {
            return (From.CompareTo(other.From) >= 0 && From.CompareTo(other.To) <= 0) ||
                   (To.CompareTo(other.From) >= 0 && To.CompareTo(other.To) <= 0) ||
                   (From.CompareTo(other.From) <= 0 && To.CompareTo(other.To) >= 0);
        }

        //Generated by IDE
        protected bool Equals(Range<T> other)
        {
            return EqualityComparer<T>.Default.Equals(From, other.From) && EqualityComparer<T>.Default.Equals(To, other.To);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj is Range<T> other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return (EqualityComparer<T>.Default.GetHashCode(From) * 397) ^ EqualityComparer<T>.Default.GetHashCode(To);
            }
        }

        public static bool operator ==(Range<T> left, Range<T> right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Range<T> left, Range<T> right)
        {
            return !Equals(left, right);
        }
    }
}